/* ── English language strings ── */
window.LANG_EN = {
  menuFile:'File', menuOptions:'Options', menuHelp:'Help',
  menuLanguage:'Language...', menuAbout:'About', menuVersions:'Versions', menuPresets:'Port Presets...', menuCountries:'Country IP Library...', menuDefaults:'Default Scan Values...',
  btnStart:'▶ Start', btnStop:'■ Stop', btnClear:'✕ Clear',
  btnMyIp:'🌐 My External IP', btnMyLocalIp:'🏠 My Local IP', btnLocalSubnets:'🧭 Local Subnets', btnCopy:'📋 Copy', btnUse:'➤ Use',
  scanSettings:'Scan Settings', ipRange:'IP Range:', threads:'Threads:', delayMs:'Delay (ms):',
  modeCam:'📹 Cameras', modePrint:'🖨️ Printers',
  modeFolder:'📁 Folders / HTTP', modeRouter:'🌐 Routers',
  modeNas:'💾 NAS', modeAll:'🔍 All',
  hintCam:'Ports: 80, 8080, 8081, 443, 554(RTSP), 9000, 37777(Dahua), 34567(DVR)',
  hintPrint:'Ports: 80, 443, 631(IPP), 9100(RAW), 8080',
  hintFolder:'Ports: 80, 8080, 8888, 21(FTP), 3000, 8000 — folder listing, FTP',
  hintRouter:'Ports: 80, 443, 8080, 8443, 10000(Webmin)',
  hintNas:'Synology 5000/5001, QNAP 8080, Proxmox 8006, TrueNAS 80/443',
  hintAll:'All known ports at once — slower, most thorough',
  labelChecked:'Checked:', labelFound:'Found:', labelPorts:'Ports:',
  colIp:'IP Address', colPing:'Ping', colHostname:'Hostname', colPorts:'Ports', colLinks:'Paths / Links',
  emptyRow:'No results. Configure IP range and click Start.',
  emptyScanning:'Scanning…', emptyNone:'No active hosts found.',
  detailGeo:'🌍 Geolocation / ISP', detailDevice:'🖥 Device Identification',
  detailTitle:'📄 HTTP Page Title', detailAccess:'🔑 Access',
  geoLocal:'Local address — geolocation unavailable',
  geoError:'Failed to fetch data',
  geoCountry:'Country:', geoIsp:'ISP:', geoAs:'AS:',
  deviceFavicon:'Favicon:', deviceFaviconYes:'✔ Yes (web panel)', deviceFaviconNo:'✘ None',
  deviceType:'Type:', deviceSuggestion:'Hint:', deviceUnknown:'Unknown device type',
  titleExtOnly:'Title: external IPs only', titleUnavailable:'Title: unavailable',
  titleLabel:'Page title:', accessLabel:'Snapshot:',
  accessOpen:'🔓 Accessible without password',
  accessClosed:'Requires authorization or unavailable',
  loading:'Loading…', analyzing:'Analyzing…', checking:'Checking…',
  localSubnetsFound:(n)=>`${n} subnet(s) detected`, localSubnetsNone:'No local subnet found',
  localDetectUnsupported:'Local network detection is not supported in this browser/context',
  localIpDetectError:'Local IP detection failed (WebRTC blocked or unavailable)',
  previewOpen:'↗ Open', previewClose:'✕',
  statusReady:'Ready.', statusCleared:'Cleared.',
  errInvalidIp:'Invalid IPv4 address.',
  errIpRange:'FROM address must be ≤ TO.',
  errNoPorts:'No ports selected in preset.',
  statusScanning:(n,p)=>`Scanning ${n} addresses × ${p} ports…`,
  statusLarge:(n,p,t)=>`Large range: ${n} addresses × ${p} ports. Est. ${t}…`,
  statusStopped:(n)=>`Stopped after ${n} addresses.`,
  statusDone:(h,p)=>`Done. Found ${h} hosts (${p} ports).`,
  statusNone:'Scan complete — no active hosts.',
  statusHosts:(n)=>`${n} hosts`,
  ctxCopyIp:'Copy IP Address', ctxCopyPorts:'Copy Ports', ctxHostname:'Hostname (reverse DNS)', ctxScanAllPorts:'Scan this IP (all ports)',
  ctxOpenBrowser:'Open in Browser', ctxPreview:'Preview here',
  labelPreset:'Preset:', labelPorts2:'Ports:',
  presetAdd:'+ Add', presetDel:'✕ Delete',
  presetEdit:'Edit preset', presetName:'Name:',
  presetPorts:'Ports:', presetSave:'💾 Save',
  presetHint:'Enter port numbers separated by commas, e.g.: 80, 443, 8080, 554',
  dlgTitle:'Options', dlgLang:'Language:',
  dlgDefaults:'Default Scan Values:', dlgDefaultThreads:'Threads:', dlgDefaultDelay:'Delay (ms):',
  dlgLangEn:'English', dlgLangPl:'Polski',
  menuClippy:'📎 Assistant',
  dlgOk:'OK', dlgCancel:'Cancel', dlgClose:'Close', dlgVersionsTitle:'Versions',
  dlgExternalIpTitle:'External IP Range', dlgExternalIpDetected:'External IP scan detected', dlgExternalIpContinue:'OK - Continue',
  dlgExternalIpMsg:(startIp, endIp)=>`The range <b>${startIp} - ${endIp}</b> contains <b>public (external) IP addresses</b>.<br><br>Scanning external addresses without authorization may be illegal and against terms of service of your ISP.<br><br>Proceed only if you own or have explicit permission to scan these addresses.`,
  dlgLargeRangeTitle:'Large Scan Range', dlgLargeRangeHead:'Are you sure?',
  dlgLargeRangeMsg:(count)=>`The selected range contains ${count} IP addresses. Scanning a large range may take a long time. Do you want to continue?`,
  portRtsp:'RTSP stream likely available',
  portIpp:'Printer (IPP)', portRaw:'Printer (RAW)',
  portSyn:'Synology NAS?', portProx:'Proxmox VE?',
  tagVpn:'VPN/Proxy', tagDc:'Datacenter', tagRecognized:'IDENTIFIED',
  notepadDesktop:'Notepad',
  notepadWinTitle:'Notepad – About',
  previewBlocked:'Device blocks embedding (X-Frame-Options).',
  previewBlockedLink:'Open directly in new tab →',
  btnImportTrace:'Import Trace', btnClearGraph:'Clear Graph', graphCleared:'Trace routes cleared.', btnClearTopoFilters:'Clear Filters', topoFiltersLabel:'Filters:', mapLiveLabel:'Live scan visualization',
  filterAllPorts:'All ports', filterPortLabel:'port', filterSubnetLabel:'subnet', filterPingLabel:'ping', filterPingPlaceholder:'Max ms',
  topologyStatus:(n)=>`Topology view · ${n} visible hosts`,
  topologyFilteredStatus:(n)=>`Topology view · ${n} filtered hosts`,
  traceRoutesLabel:'trace routes',
  traceDlgTitle:'Import traceroute', traceTargetLabel:'Target IP:', traceHint:'Paste output from tracert or traceroute.', traceDlgHint:'Import a real traceroute path for the selected host.',
  traceErrTarget:'Enter a valid target IPv4 address.', traceErrTargetOrHost:'Enter a valid target IP or hostname.', traceErrParse:'Could not parse any hops from the pasted output.',
  traceImported:(n, ip)=>`Imported ${n} hops for ${ip}.`, traceImportedStatus:(ip, n)=>`Trace route imported for ${ip} (${n} hops).`, traceHopCopied:(ip)=>`Hop IP copied: ${ip}`,
  btnTraceAuto:'Auto Trace', traceAutoRunning:'Running traceroute...', traceAutoDesktopOnly:'Auto trace works only in Tauri desktop build.',
  traceAutoFailed:(msg)=>`Traceroute failed: ${msg}`,
  btnTraceSave:'Import',
  menuEdit:'Edit',
  notepadStatus:'NetRecon IP Auditor · License: Free to use',
  cmdWinTitle:'Console Log', cmdMenuFile:'File', cmdSaveLogs:'💾 Save logs...',
  cmdFilter:'Filter:', cmdFilterAll:'-- All --', cmdFilterScan:'Scan',
  cmdFilterTracert:'Tracert', cmdFilterMacro:'Macro', cmdFilterSpeed:'Speed',
  cmdBtnFilter:'Filter', cmdBtnClearLog:'Clear',
  speedWinTitle:'Internet Speed Test',
  speedLabelDownload:'Download', speedLabelPing:'Ping', speedLabelUpload:'Upload',
  speedMbps:'Mbps', speedMs:'ms',
  speedReady:'Click Start to measure ping, download and upload.',
  speedBtnStart:'▶ Start test',
  protoWinTitle:'Visual Programming Prototype',
  protoStatusText:'Status: Prototype mode (UI concept only). Link mode: click OUT anchor, then click IN anchor.',
  macroWinTitle:'Macros', macroCtxDelete:'🗑 Delete macro',
  countrySearchPlaceholder:'Search country…', countryRangeHint:'Click a range to select it, then click Use.',
  btnCountryUse:'➤ Use range', btnCountryUseAll:'➤ Use all',
  customizeTitle:'Customization – Toolbar', customizeToolbarLegend:'Toolbar buttons',
  customizeGlobe:'🌍 Globe (World Map)', customizeConsole:'⌨ Console',
  customizeMacro:'📁 Macro', customizeSpeed:'📶 Speed Test',
  customizeProto:'🧩 Prototype', customizeTopology:'🕸 Topology',
  customizeSkinLegend:'Skin', skinClassic:'Classic', skinGlass:'Glass', skinWorkbench:'Workbench Night',
  globeWinTitle:'Network Map – IP Scan Results',
  btnMapGlobe:'Globe', btnMapTopology:'Topology',
  globeStatusDefault:'Drag to rotate · Click country to scan · Click dot to preview',
  globeAutoRotate:'Auto-rotate',
  scanCountryDlgTitle:'Scan Country', dlgYes:'Yes', dlgNo:'No',
  ctxDetailGeo:'🌍 Geolocation / ISP', ctxDetailDevice:'🖥 Device Identification',
  ctxDetailTitle:'📄 HTTP Page Title', ctxDetailAccess:'🔑 Access / Snapshot',
};
