/* ── English language strings ── */
window.LANG_EN = {
  menuFile:'File', menuOptions:'Options', menuTools:'Tools', menuHelp:'Help',
  menuLanguage:'Language...', menuAbout:'About', menuVersions:'Versions', menuDownload:'📥 Download', menuPresets:'Port Presets...', menuCountries:'Country IP Library...', menuDefaults:'Default Scan Values...',
  btnStart:'▶ Start', btnStop:'■ Stop', btnClear:'✕ Clear', btnGlobe:'🌍 Globe',
  btnConsole:'⌨ Console', btnMacro:'📁 Macro', btnSpeed:'📶 Speed', btnProto:'🧩 Prototype', btnTopology:'🕸 Topology', btnWifiRadar:'📍 WiFi Radar',
  btnBtDetector:'🔵 BT Detector', btnBtDetectorMenu:'🔵 Bluetooth Detector...',
  btWinTitle:'Bluetooth Detector', btScanSettings:'Scan settings', btDuration:'Duration:', btScan:'Scan', btStop:'Stop',
  btNearbyDevices:'Nearby devices', btProperties:'Properties', btReady:'Ready.', btReadyAction:'Ready - click Scan to search for nearby Bluetooth devices.',
  btNoDevicesFound:'No devices found.', btSelectDevice:'Select a device from the list.', btNoServices:'No services advertised.',
  btDesktopOnly:'Bluetooth Detector is available only in desktop (Tauri) mode.',
  btStatusScanning:(s)=>`Scanning for Bluetooth devices (${s}s)...`, btStatusFound:(n)=>`Found ${n} device(s).`,
  btStatusNoDevices:'Scan complete - no devices detected nearby.', btStatusError:(e)=>`Error: ${e}`,
  btStatusStopRequested:'Stop requested - waiting for scan to finish...',
  btLabelName:'Name', btLabelAddress:'Address', btLabelSignal:'Signal (RSSI)', btLabelConnectable:'Connectable', btLabelSource:'Source',
  btServicesHead:'Services / UUIDs', btUnknown:'Unknown', btYes:'Yes', btNo:'No',
  btnMyIp:'🌐 My External IP', btnMyLocalIp:'🏠 My Local IP', btnLocalSubnets:'🧭 Local Subnets', btnCopy:'📋 Copy', btnUse:'➤ Use',
  scanSettings:'Scan Settings', ipRange:'IP Range:', threads:'Threads:', delayMs:'Delay (ms):',
  modeCam:'📹 Cameras', modePrint:'🖨️ Printers',
  modeFolder:'📁 Folders / HTTP', modeRouter:'🌐 Routers',
  modeNas:'💾 NAS', modeAll:'🔍 All',
  hintCam:'Ports: 80, 8080, 8081, 443, 554(RTSP), 9000, 37777(Dahua), 34567(DVR)',
  hintPrint:'Ports: 80, 443, 631(IPP), 9100(RAW), 8080',
  hintFolder:'Ports: 80, 8080, 8888, 21(FTP), 3000, 8000 — folder listing, FTP',
  hintRouter:'Ports: 80, 443, 8080, 8443, 10000(Webmin)',
  hintNas:'Synology 5000/5001, QNAP 8080, Proxmox 8006, TrueNAS 80/443',
  hintAll:'All known ports at once — slower, most thorough',
  labelChecked:'Checked:', labelFound:'Found:', labelPorts:'Ports:',
  colIp:'IP Address', colPing:'Ping', colHostname:'Hostname', colPorts:'Ports', colLinks:'Paths / Links',
  filterShow:'Show:', filterAll:'All', filterFavorites:'★ Favorites', filterActive:'Active', filterDead:'Dead',
  emptyRow:'No results. Configure IP range and click Start.',
  emptyScanning:'Scanning…', emptyNone:'No active hosts found.',
  detailGeo:'🌍 Geolocation / ISP', detailDevice:'🖥 Device Identification',
  detailTitle:'📄 HTTP Page Title', detailAccess:'🔑 Access',
  geoLocal:'Local address — geolocation unavailable',
  geoError:'Failed to fetch data',
  geoCountry:'Country:', geoIsp:'ISP:', geoAs:'AS:',
  deviceFavicon:'Favicon:', deviceFaviconYes:'✔ Yes (web panel)', deviceFaviconNo:'✘ None',
  deviceType:'Type:', deviceSuggestion:'Hint:', deviceUnknown:'Unknown device type',
  titleExtOnly:'Title: external IPs only', titleUnavailable:'Title: unavailable',
  titleLabel:'Page title:', accessLabel:'Snapshot:',
  accessOpen:'🔓 Accessible without password',
  accessClosed:'Requires authorization or unavailable',
  loading:'Loading…', analyzing:'Analyzing…', checking:'Checking…',
  localSubnetsFound:(n)=>`${n} subnet(s) detected`, localSubnetsNone:'No local subnet found',
  localDetectUnsupported:'Local network detection is not supported in this browser/context',
  localIpDetectError:'Local IP detection failed (WebRTC blocked or unavailable)',
  previewOpen:'↗ Open', previewClose:'✕',
  statusReady:'Ready.', statusCleared:'Cleared.',
  errInvalidIp:'Invalid IPv4 address.',
  errIpRange:'FROM address must be ≤ TO.',
  closeConfirm:'Are you sure you want to close the scanner?',
  errNoPorts:'No ports selected in preset.',
  statusScanning:(n,p)=>`Scanning ${n} addresses × ${p} ports…`,
  statusLarge:(n,p,t)=>`Large range: ${n} addresses × ${p} ports. Est. ${t}…`,
  statusStopped:(n)=>`Stopped after ${n} addresses.`,
  statusDone:(h,p)=>`Done. Found ${h} hosts (${p} ports).`,
  statusNone:'Scan complete — no active hosts.',
  statusHosts:(n)=>`${n} hosts`,
  ctxCopyIp:'Copy IP Address', ctxCopyPorts:'Copy Ports', ctxHostname:'Hostname (reverse DNS)', ctxScanAllPorts:'Scan this IP (all ports)',
  ctxOpenBrowser:'Open in Browser', ctxPreview:'Preview here',
  labelPreset:'Preset:', labelPorts2:'Ports:',
  presetAdd:'+ Add', presetDel:'✕ Delete',
  presetEdit:'Edit preset', presetName:'Name:',
  presetPorts:'Ports:', presetSave:'💾 Save',
  presetHint:'Enter port numbers separated by commas, e.g.: 80, 443, 8080, 554',
  dlgTitle:'Options', dlgLang:'Language:',
  dlgDefaults:'Default Scan Values:', dlgDefaultThreads:'Threads:', dlgDefaultDelay:'Delay (ms):', dlgDefaultDelayPerPort:'Delay per port (ms):',
  tipThreads:'Number of parallel scanning threads (2–64). More = faster, but higher network load.',
  tipIpDelay:'Delay (ms) between consecutive IP addresses scanned by each thread. 0 = no delay.',
  tipBatchSize:'Number of ports scanned simultaneously in parallel mode (10–500). Larger batch = faster, but more concurrent connections.',
  tipParallel:'All ports in a batch are scanned simultaneously — fastest mode.',
  tipSequential:'Ports are scanned one by one with a set delay — slower, but less visible to IDS/firewall.',
  tipPortDelay:'Delay (ms) between scanning consecutive ports in sequential mode (0–1000).',
  dlgLangEn:'English', dlgLangPl:'Polski',
  menuClippy:'📎 Assistant',
  dlgOk:'OK', dlgCancel:'Cancel', dlgClose:'Close', dlgVersionsTitle:'Versions',
  dlgExternalIpTitle:'External IP Range', dlgExternalIpDetected:'External IP scan detected', dlgExternalIpContinue:'OK - Continue',
  dlgExternalIpMsg:(startIp, endIp)=>`The range <b>${startIp} - ${endIp}</b> contains <b>public (external) IP addresses</b>.<br><br>Scanning external addresses without authorization may be illegal and against terms of service of your ISP.<br><br>Proceed only if you own or have explicit permission to scan these addresses.`,
  dlgLargeRangeTitle:'Large Scan Range', dlgLargeRangeHead:'Are you sure?',
  dlgLargeRangeMsg:(count)=>`The selected range contains ${count} IP addresses. Scanning a large range may take a long time. Do you want to continue?`,
  portRtsp:'RTSP stream likely available',
  portIpp:'Printer (IPP)', portRaw:'Printer (RAW)',
  portSyn:'Synology NAS?', portProx:'Proxmox VE?',
  tagVpn:'VPN/Proxy', tagDc:'Datacenter', tagRecognized:'IDENTIFIED',
  notepadDesktop:'Notepad',
  notepadWinTitle:'About',
  previewBlocked:'Device blocks embedding (X-Frame-Options).',
  previewBlockedLink:'Open directly in new tab →',
  btnImportTrace:'Import Trace', btnClearGraph:'Clear Graph', graphCleared:'Trace routes cleared.', btnClearTopoFilters:'Clear Filters', topoFiltersLabel:'Filters:', mapLiveLabel:'Live scan visualization',
  filterAllPorts:'All ports', filterPortLabel:'port', filterSubnetLabel:'subnet', filterPingLabel:'ping', filterPingPlaceholder:'Max ms',
  topologyStatus:(n)=>`Topology view · ${n} visible hosts`,
  topologyFilteredStatus:(n)=>`Topology view · ${n} filtered hosts`,
  traceRoutesLabel:'trace routes',
  traceDlgTitle:'Import traceroute', traceTargetLabel:'Target IP:', traceHint:'Paste output from tracert or traceroute.', traceDlgHint:'Import a real traceroute path for the selected host.',
  traceErrTarget:'Enter a valid target IPv4 address.', traceErrTargetOrHost:'Enter a valid target IP or hostname.', traceErrParse:'Could not parse any hops from the pasted output.',
  traceImported:(n, ip)=>`Imported ${n} hops for ${ip}.`, traceImportedStatus:(ip, n)=>`Trace route imported for ${ip} (${n} hops).`, traceHopCopied:(ip)=>`Hop IP copied: ${ip}`,
  btnTraceAuto:'Auto Trace', traceAutoRunning:'Running traceroute...', traceAutoDesktopOnly:'Auto trace works only in Tauri desktop build.',
  traceAutoFailed:(msg)=>`Traceroute failed: ${msg}`,
  btnTraceSave:'Import',
  menuEdit:'Edit',
  cmdWinTitle:'Console Log', cmdMenuFile:'File', cmdSaveLogs:'💾 Save logs...',
  cmdFilter:'Filter:', cmdFilterAll:'-- All --', cmdFilterScan:'Scan',
  cmdFilterTracert:'Tracert', cmdFilterMacro:'Macro', cmdFilterSpeed:'Speed',
  cmdBtnFilter:'Filter', cmdBtnClearLog:'Clear',
  speedWinTitle:'Internet Speed Test',
  speedLabelDownload:'Download', speedLabelPing:'Ping', speedLabelUpload:'Upload',
  speedMbps:'Mbps', speedMs:'ms',
  speedReady:'Click Start to measure ping, download and upload.',
  speedBtnStart:'▶ Start test',
  protoWinTitle:'Visual Programming Prototype',
  protoStatusText:'Status: Prototype mode (UI concept only). Link mode: click OUT anchor, then click IN anchor.',
  macroWinTitle:'Macros', macroCtxDelete:'🗑 Delete macro',
  countrySearchPlaceholder:'Search country…', countryRangeHint:'Click a range to select it, then click Use.',
  btnCountryUse:'➤ Use range', btnCountryUseAll:'➤ Use all',
  customizeTitle:'Customization – Toolbar', customizeToolbarLegend:'Toolbar buttons',
  customizeGlobe:'🌍 Globe (World Map)', customizeConsole:'⌨ Console',
  customizeMacro:'📁 Macro', customizeSpeed:'📶 Speed Test',
  customizeProto:'🧩 Prototype', customizeTopology:'🕸 Topology',
  customizeSkinLegend:'Skin', skinClassic:'Classic', skinGlass:'Glass', skinWorkbench:'Workbench Night', skinPurpleDark:'Purple Dark', skinBlackFlat:'Black Flat', skinRetrogray:'Retro Gray',
  globeWinTitle:'Network Map – IP Scan Results',
  topoWinTitle:'Network Topology',
  btnMapGlobe:'Globe', btnMapTopology:'Topology',
  globeStatusDefault:'Drag to rotate · Click country to scan · Click dot to preview',
  topoStatusDefault:'Topology view · Click host to preview · Rings show subnet depth',
  globeAutoRotate:'Auto-rotate',
  scanCountryDlgTitle:'Scan Country', dlgYes:'Yes', dlgNo:'No',
  ctxDetailGeo:'🌍 Geolocation / ISP', ctxDetailDevice:'🖥 Device Identification',
  ctxDetailTitle:'📄 HTTP Page Title', ctxDetailAccess:'🔑 Access / Snapshot',
  btnGnss:'🛰 GNSS', btnGnssMenu:'🛰 GNSS Monitor...',
  gnssWinTitle:'GNSS Monitor', gnssPort:'Port:', gnssBaud:'Baud:',
  gnssRefreshPorts:'Refresh ports', gnssReadNow:'Read now', gnssStartLive:'Start live', gnssStopLive:'Stop',
  gnssStatus:'GNSS status', gnssSatMonitor:'Satellite monitor', gnssConstellation:'Constellation',
  gnssWifiAudit:'GPS + WiFi audit', gnssWifiScan:'Scan WiFi now', gnssAddPoint:'Add audit point', gnssExportAudit:'Export CSV',
  gnssReady:'Ready.', gnssBrowserGeo:'Browser geolocation', gnssDesktopOnly:'This action requires desktop (Tauri) mode.',
  gnssPortsLoaded:(n)=>`Ports loaded: ${n}.`, gnssErrPorts:(e)=>`Failed to load ports: ${e}`,
  gnssFix:'Fix', gnssSatsUsed:'Satellites used', gnssSatsInView:'Satellites in view', gnssSource:'Source', gnssTimeUtc:'UTC time',
  gnssReading:'Reading GNSS data...', gnssReadOk:'GNSS data updated.', gnssErrRead:(e)=>`GNSS read error: ${e}`,
  gnssWifiOk:(n)=>`WiFi scan complete. Networks: ${n}.`, gnssErrWifi:(e)=>`WiFi scan error: ${e}`,
  gnssNoAuditPoints:'No audit points yet.', gnssNeedFix:'GNSS fix is required before adding an audit point.',
  gnssPointAdded:(n)=>`Audit point added (#${n}).`,
  btnLteMenu:'📶 LTE Monitor...', lteWinTitle:'LTE Monitor',
  lteRefresh:'Refresh', lteStartLive:'Start live', lteStopLive:'Stop', lteLiveEvery:'Every (s):',
  ltePort:'Port:', lteBaud:'Baud:', lteAutoDetect:'Auto',
  lteModeAuto:'Auto', lteModeManual:'Manual',
  lteStatusTitle:'LTE status monitor', lteHandoverTitle:'Cell handover tracker',
  lteAuditTitle:'LTE + GPS audit', lteAddPoint:'Add point', lteExportAudit:'Export CSV',
  lteCorrelationTitle:'Speed + quality correlation', lteRunSpeed:'Run sample', lteExportCorrelation:'Export CSV',
  lteWatchdogTitle:'LTE internet watchdog', lteStartWatchdog:'Start watchdog', lteStopWatchdog:'Stop',
  lteReady:'Ready.', lteNoData:'No LTE/network data yet.', lteStatusUpdated:'Status updated.',
  lteQualityScore:'Quality score', lteRadioTech:'Radio', lteEffectiveType:'Effective type', lteConnType:'Connection type',
  lteMode:'Mode',
  lteOperator:'Operator', lteBand:'Band', lteEarfcn:'EARFCN', lteCellId:'Cell ID', lteTac:'TAC',
  lteRsrp:'RSRP', lteRsrq:'RSRQ', lteSinr:'SINR', lteSource:'Source', lteSerialModeActive:'serial modem',
  lteDownlink:'Downlink', lteRtt:'RTT', ltePublicIp:'Public IP', lteLocalIp:'Local IP', lteOnline:'Online', lteUpdatedAt:'Updated',
  lteNoHandover:'No handovers yet.', lteHandoverReasonProfileChange:'network profile changed',
  lteNoAuditPoints:'No audit points yet.', lteAuditPointAdded:(n)=>`Audit point added (#${n}).`,
  lteNoCorrelation:'No correlation samples yet.', lteCorrAdded:(n)=>`Correlation sample added (#${n}).`,
  lteCorrInsufficient:'Correlation: at least 3 samples required.', lteCorrNow:'Correlation (quality vs download)',
  lteWatchdogEmpty:'No watchdog events yet.', lteWatchdogFail:'Watchdog: connectivity issue detected.',
  lteWatchdogOk:(rtt)=>`Watchdog OK (${rtt} ms).`, lteWdOk:'OK', lteWdFail:'FAIL',
  btnSniffer:'🔎 Sniffer', btnSnifferMenu:'🔎 Network Sniffer...',
  snifferWinTitle:'Network Sniffer',
  snifferAll:'All', snifferRefresh:'↻ Refresh', snifferLive:'Live', snifferExport:'💾 Export CSV',
  snifferColPid:'PID', snifferColProc:'Process', snifferColProto:'Proto',
  snifferColLocal:'Local', snifferColRemote:'Remote', snifferColState:'State',
  snifferFilter:'Filter process / IP...',
  snifferReady:'Ready.', snifferLoading:'Refreshing connections...',
  snifferStatusDone:(n)=>`Loaded ${n} connection(s).`,
  snifferEmpty:'No connections match the current filter.',
  snifferDesktopOnly:'Network Sniffer works only in desktop (Tauri) mode.',
  snifferTotal:'Total',
  btnImgMetaMenu:'🖼 Image Metadata...', imgMetaWinTitle:'Image Metadata and Steganography Analyzer',
  imgMetaDropHint:'Drop an image here or click to browse',
  imgMetaBrowse:'Browse...', imgMetaClear:'Clear', imgMetaClearAll:'Clear all', imgMetaZeroValues:'Zero values', imgMetaCopy:'Copy', imgMetaExport:'Export TXT',
  imgMetaHideEmptyOn:'Hide empty: ON', imgMetaHideEmptyOff:'Hide empty: OFF', imgMetaHideEmptyHint:'Hide or show detected metadata fields with empty values.',
  imgMetaSection:'Section', imgMetaKey:'Field', imgMetaValue:'Value',
  imgMetaReady:'Ready. Open an image to analyze its metadata (steganography check enabled).',
  imgMetaLoading:'Reading file...', imgMetaAnalyzing:'Analyzing...',
  imgMetaDone:(n)=>`Found ${n} metadata field(s).`,
  imgMetaNoMeta:'No metadata found in this file.',
  imgMetaStegoChecked:'Steganography check enabled.',
  imgMetaStegoNotDetected:'No hidden trailing data detected.',
  imgMetaStegoDetected:(n)=>`Potential hidden trailing data detected: ${n} byte(s).`,
  imgMetaDesktopHint:'Full EXIF and GPS data requires desktop (Tauri) mode.',
  btnPhoneLookupMenu:'📱 Phone Reverse Lookup...', phoneLookupWinTitle:'Phone Reverse Lookup',
  phoneLookupApiKeys:'API Keys Configuration',
  phoneLookupInput:'Phone Number', phoneLookupSearchBtn:'Search',
  phoneLookupReady:'Ready. Enter a phone number to search.',
  btnSave:'Save', btnClear:'Clear',
  imgMetaErrRead:'Failed to read file.',
  imgMetaInfo:'Info', imgMetaInfoTitle:'Analyzed metadata fields',
  imgMetaEdited:'Edited locally.',
  imgMetaCopied:'Copied to clipboard.',
};
