/* ── Polish language strings ── */
window.LANG_PL = {
  menuFile:'Plik', menuOptions:'Opcje', menuHelp:'Pomoc',
  menuLanguage:'Język...', menuAbout:'O programie', menuVersions:'Wersje', menuPresets:'Presety portów...', menuCountries:'Biblioteka krajów IP...', menuDefaults:'Domyślne wartości skanowania...',
  btnStart:'▶ Start', btnStop:'■ Stop', btnClear:'✕ Wyczyść', btnGlobe:'🌍 Mapa',
  btnMyIp:'🌐 Moje zewnętrzne IP', btnMyLocalIp:'🏠 Moje lokalne IP', btnLocalSubnets:'🧭 Lokalne podsieci', btnCopy:'📋 Kopiuj', btnUse:'➤ Użyj',
  scanSettings:'Ustawienia skanowania', ipRange:'IP Range:', threads:'Wątki:', delayMs:'Opóźnienie (ms):',
  modeCam:'📹 Kamery', modePrint:'🖨️ Drukarki',
  modeFolder:'📁 Foldery / HTTP', modeRouter:'🌐 Routery',
  modeNas:'💾 NAS', modeAll:'🔍 Wszystko',
  hintCam:'Porty: 80, 8080, 8081, 443, 554(RTSP), 9000, 37777(Dahua), 34567(DVR)',
  hintPrint:'Porty: 80, 443, 631(IPP), 9100(RAW), 8080',
  hintFolder:'Porty: 80, 8080, 8888, 21(FTP), 3000, 8000 — listing folderów, FTP',
  hintRouter:'Porty: 80, 443, 8080, 8443, 10000(Webmin)',
  hintNas:'Synology 5000/5001, QNAP 8080, Proxmox 8006, TrueNAS 80/443',
  hintAll:'Wszystkie znane porty jednocześnie — wolniejszy, najdokładniejszy',
  labelChecked:'Sprawdzono:', labelFound:'Znaleziono:', labelPorts:'Portów:',
  colIp:'Adres IP', colPing:'Ping', colHostname:'Hostname', colPorts:'Porty', colLinks:'Ścieżki / Linki',
  emptyRow:'Brak wyników. Skonfiguruj zakres IP i kliknij Start.',
  emptyScanning:'Skanowanie…', emptyNone:'Nie znaleziono aktywnych hostów.',
  detailGeo:'🌍 Geolokalizacja / ISP', detailDevice:'🖥 Identyfikacja urządzenia',
  detailTitle:'📄 Tytuł strony HTTP', detailAccess:'🔑 Dostęp',
  geoLocal:'Adres lokalny — geolokalizacja niedostępna',
  geoError:'Błąd pobierania danych',
  geoCountry:'Kraj:', geoIsp:'ISP:', geoAs:'AS:',
  deviceFavicon:'Favicon:', deviceFaviconYes:'✔ Tak (panel webowy)', deviceFaviconNo:'✘ Brak',
  deviceType:'Typ:', deviceSuggestion:'Sugestia:', deviceUnknown:'Nieznany typ urządzenia',
  titleExtOnly:'Tytuł: tylko dla zewnętrznych IP', titleUnavailable:'Tytuł: niedostępny',
  titleLabel:'Tytuł strony:', accessLabel:'Snapshot:',
  accessOpen:'🔓 Dostępny bez hasła',
  accessClosed:'Wymaga autoryzacji lub brak',
  loading:'Pobieranie…', analyzing:'Analiza…', checking:'Sprawdzanie…',
  localSubnetsFound:(n)=>`Wykryto podsieci: ${n}`, localSubnetsNone:'Nie wykryto lokalnej podsieci',
  localDetectUnsupported:'Wykrywanie lokalnej sieci nie jest wspierane w tej przeglądarce/kontekście',
  localIpDetectError:'Nie udało się wykryć lokalnego IP (WebRTC zablokowane lub niedostępne)',
  previewOpen:'↗ Otwórz', previewClose:'✕',
  statusReady:'Gotowy.', statusCleared:'Wyczyszczono.',
  errInvalidIp:'Podaj poprawne adresy IPv4.',
  errIpRange:'Adres OD musi być ≤ DO.',
  closeConfirm:'Czy na pewno chcesz zamknąć skaner?',
  errNoPorts:'Wybierz co najmniej jeden port w presecie.',
  statusScanning:(n,p)=>`Skanuję ${n} adresów × ${p} portów…`,
  statusLarge:(n,p,t)=>`Duży zakres: ${n} adresów × ${p} portów. Est. ${t}…`,
  statusStopped:(n)=>`Zatrzymano po ${n} adresach.`,
  statusDone:(h,p)=>`Zakończono. Znaleziono ${h} hostów (${p} portów).`,
  statusNone:'Skan zakończony — brak aktywnych hostów.',
  statusHosts:(n)=>`${n} hostów`,
  ctxCopyIp:'Kopiuj adres IP', ctxCopyPorts:'Kopiuj porty', ctxHostname:'Hostname (reverse DNS)', ctxScanAllPorts:'Skanuj to IP (wszystkie porty)',
  ctxOpenBrowser:'Otwórz w przeglądarce', ctxPreview:'Podgląd tutaj',
  labelPreset:'Preset:', labelPorts2:'Porty:',
  presetAdd:'+ Dodaj', presetDel:'✕ Usuń',
  presetEdit:'Edytuj preset', presetName:'Nazwa:',
  presetPorts:'Porty:', presetSave:'💾 Zapisz',
  presetHint:'Wpisz numery portów po przecinku, np.: 80, 443, 8080, 554',
  dlgTitle:'Opcje', dlgLang:'Język:',
  dlgDefaults:'Domyślne wartości skanowania:', dlgDefaultThreads:'Wątki:', dlgDefaultDelay:'Opóźnienie (ms):',
  dlgLangEn:'English', dlgLangPl:'Polski',
  menuClippy:'📎 Asystent',
  dlgOk:'OK', dlgCancel:'Anuluj', dlgClose:'Zamknij', dlgVersionsTitle:'Wersje',
  dlgExternalIpTitle:'Zewnętrzny zakres IP', dlgExternalIpDetected:'Wykryto skanowanie zewnętrznych IP', dlgExternalIpContinue:'OK - Kontynuuj',
  dlgExternalIpMsg:(startIp, endIp)=>`Zakres <b>${startIp} - ${endIp}</b> zawiera <b>publiczne (zewnętrzne) adresy IP</b>.<br><br>Skanowanie zewnętrznych adresów bez autoryzacji może być nielegalne i niezgodne z regulaminem dostawcy Internetu.<br><br>Kontynuuj tylko wtedy, gdy jesteś właścicielem tych adresów lub masz wyraźną zgodę na skanowanie.`,
  dlgLargeRangeTitle:'Duży zakres skanowania', dlgLargeRangeHead:'Czy na pewno?',
  dlgLargeRangeMsg:(count)=>`Wybrany zakres zawiera ${count} adresów IP. Skanowanie dużego zakresu może potrwać długo. Czy chcesz kontynuować?`,
  portRtsp:'RTSP stream prawdopodobnie dostępny',
  portIpp:'Drukarka (IPP)', portRaw:'Drukarka (RAW)',
  portSyn:'Synology NAS?', portProx:'Proxmox VE?',
  tagVpn:'VPN/Proxy', tagDc:'Datacenter', tagRecognized:'ROZPOZNANY',
  notepadDesktop:'Notatnik',
  notepadWinTitle:'About',
  previewBlocked:'Urządzenie blokuje osadzanie (X-Frame-Options).',
  previewBlockedLink:'Otwórz w nowej karcie →',
  btnImportTrace:'Importuj Trace', btnClearGraph:'Wyczyść graf', graphCleared:'Trasy zostały wyczyszczone.', btnClearTopoFilters:'Wyczyść filtry', topoFiltersLabel:'Filtry:', mapLiveLabel:'Wizualizacja na żywo',
  filterAllPorts:'Wszystkie porty', filterPortLabel:'port', filterSubnetLabel:'podsieć', filterPingLabel:'ping', filterPingPlaceholder:'Maks ms',
  topologyStatus:(n)=>`Widok topologii · ${n} widocznych hostów`,
  topologyFilteredStatus:(n)=>`Widok topologii · ${n} hostów po filtrach`,
  traceRoutesLabel:'tras trace',
  traceDlgTitle:'Import traceroute', traceTargetLabel:'Docelowe IP:', traceHint:'Wklej wynik z tracert albo traceroute.', traceDlgHint:'Zaimportuj prawdziwą trasę hop-by-hop dla wybranego hosta.',
  traceErrTarget:'Podaj poprawny docelowy adres IPv4.', traceErrTargetOrHost:'Podaj poprawny docelowy adres IP lub hostname.', traceErrParse:'Nie udało się odczytać hopów z wklejonego wyniku.',
  traceImported:(n, ip)=>`Zaimportowano ${n} hopów dla ${ip}.`, traceImportedStatus:(ip, n)=>`Zaimportowano trasę dla ${ip} (${n} hopów).`, traceHopCopied:(ip)=>`Skopiowano IP hopa: ${ip}`,
  btnTraceAuto:'Auto Trace', traceAutoRunning:'Uruchamiam traceroute...', traceAutoDesktopOnly:'Auto trace działa tylko w wersji desktopowej Tauri.',
  traceAutoFailed:(msg)=>`Traceroute nie powiodło się: ${msg}`,
  btnTraceSave:'Importuj',
  menuEdit:'Edycja',
  cmdWinTitle:'Log konsoli', cmdMenuFile:'Plik', cmdSaveLogs:'💾 Zapisz logi...',
  cmdFilter:'Filtr:', cmdFilterAll:'-- Wszystko --', cmdFilterScan:'Skan',
  cmdFilterTracert:'Tracert', cmdFilterMacro:'Makro', cmdFilterSpeed:'Szybkość',
  cmdBtnFilter:'Filtruj', cmdBtnClearLog:'Wyczyść',
  speedWinTitle:'Test prędkości internetu',
  speedLabelDownload:'Pobieranie', speedLabelPing:'Ping', speedLabelUpload:'Wysyłanie',
  speedMbps:'Mbps', speedMs:'ms',
  speedReady:'Kliknij Start, aby zmierzyć ping, download i upload.',
  speedBtnStart:'▶ Start test',
  protoWinTitle:'Prototyp Visual Programming',
  protoStatusText:'Status: Tryb prototypu (tylko koncepcja UI). Tryb łączy: kliknij kotwicę OUT, potem IN.',
  macroWinTitle:'Makra', macroCtxDelete:'🗑 Skasuj makro',
  countrySearchPlaceholder:'Szukaj kraju…', countryRangeHint:'Kliknij zakres, a następnie kliknij Użyj.',
  btnCountryUse:'➤ Użyj zakresu', btnCountryUseAll:'➤ Użyj wszystkich',
  customizeTitle:'Dostosowanie – Pasek narzędzi', customizeToolbarLegend:'Przyciski paska',
  customizeGlobe:'🌍 Glob (Mapa świata)', customizeConsole:'⌨ Konsola',
  customizeMacro:'📁 Makro', customizeSpeed:'📶 Test prędkości',
  customizeProto:'🧩 Prototyp', customizeTopology:'🕸 Topologia',
  customizeSkinLegend:'Wygląd', skinClassic:'Klasyczny', skinGlass:'Szklany', skinWorkbench:'Ciemny motyw',
  globeWinTitle:'Mapa sieci – Wyniki skanowania',
  btnMapGlobe:'Glob', btnMapTopology:'Topologia',
  globeStatusDefault:'Przeciągnij aby obrócić · Kliknij kraj aby skanować · Kliknij punkt aby podejrzeć',
  globeAutoRotate:'Auto-obrót',
  scanCountryDlgTitle:'Skanuj kraj', dlgYes:'Tak', dlgNo:'Nie',
  ctxDetailGeo:'🌍 Geolokalizacja / ISP', ctxDetailDevice:'🖥 Identyfikacja urządzenia',
  ctxDetailTitle:'📄 Tytuł strony HTTP', ctxDetailAccess:'🔑 Dostęp / Snapshot',
};
