// Auto-generated by scripts/sync-version.js from package.json - do not edit by hand.
(function () {
  window.NetReconNewUICore = window.NetReconNewUICore || {};
  window.NetReconNewUICore.APP_VERSION = "2.0.0";
})();
