/* ── Polish language strings ── */
window.LANG_PL = {
  menuFile:'Plik', menuOptions:'Opcje', menuTools:'Narzędzia', menuHelp:'Pomoc',
  menuLanguage:'Język...', menuAbout:'O programie', menuVersions:'Wersje', menuDownload:'📥 Pobierz', menuPresets:'Presety portów...', menuCountries:'Biblioteka krajów IP...', menuDefaults:'Domyślne wartości skanowania...',
  btnStart:'▶ Start', btnStop:'■ Stop', btnClear:'✕ Wyczyść', btnFactoryReset:'⟲ Resetuj wszystko', btnFactoryResetTip:'Reset całej aplikacji: usuwa zapisane dane i przeładowuje okno.', btnGlobe:'🌍 Mapa',
  btnConsole:'⌨ Konsola', btnMacro:'📁 Makro', btnSpeed:'📶 Prędkość', btnProto:'🧩 Prototyp', btnTopology:'🕸 Topologia', btnWifiRadar:'📍 WiFi Radar',
  btnBtDetector:'🔵 BT Detektor', btnBtDetectorMenu:'🔵 Bluetooth Detector...',
  btWinTitle:'Bluetooth Detector', btScanSettings:'Ustawienia skanowania', btDuration:'Czas:', btScan:'Skanuj', btStop:'Stop',
  btNearbyDevices:'Urządzenia w pobliżu', btProperties:'Właściwości', btReady:'Gotowy.', btReadyAction:'Gotowy - kliknij Skanuj, aby wyszukać urządzenia Bluetooth w pobliżu.',
  btNoDevicesFound:'Nie znaleziono urządzeń.', btSelectDevice:'Wybierz urządzenie z listy.', btNoServices:'Brak reklamowanych usług.',
  btDesktopOnly:'Bluetooth Detector działa tylko w wersji desktopowej (Tauri).',
  btStatusScanning:(s)=>`Skanowanie urządzeń Bluetooth (${s}s)...`, btStatusFound:(n)=>`Znaleziono urządzeń: ${n}.`,
  btStatusNoDevices:'Skan zakończony - nie wykryto urządzeń w pobliżu.', btStatusError:(e)=>`Błąd: ${e}`,
  btStatusStopRequested:'Żądanie zatrzymania - czekam na zakończenie skanowania...',
  btLabelName:'Nazwa', btLabelAddress:'Adres', btLabelSignal:'Sygnał (RSSI)', btLabelConnectable:'Łączność', btLabelSource:'Źródło',
  confirmFactoryReset:'To wyczyści wszystkie dane aplikacji zapisane w localStorage i zresetuje interfejs. Kontynuować?',
  btServicesHead:'Usługi / UUID', btUnknown:'Nieznane', btYes:'Tak', btNo:'Nie',
  btnMyIp:'🌐 Moje zewnętrzne IP', btnMyLocalIp:'🏠 Moje lokalne IP', btnLocalSubnets:'🧭 Lokalne podsieci', btnCopy:'📋 Kopiuj', btnUse:'➤ Użyj',
  scanSettings:'Ustawienia skanowania', ipRange:'Zakres IP:', threads:'Wątki:', delayMs:'Opóźnienie (ms):',
  modeCam:'📹 Kamery', modePrint:'🖨️ Drukarki',
  modeFolder:'📁 Foldery / HTTP', modeRouter:'🌐 Routery',
  modeNas:'💾 NAS', modeAll:'🔍 Wszystko',
  hintCam:'Porty: 80, 8080, 8081, 443, 554(RTSP), 9000, 37777(Dahua), 34567(DVR)',
  hintPrint:'Porty: 80, 443, 631(IPP), 9100(RAW), 8080',
  hintFolder:'Porty: 80, 8080, 8888, 21(FTP), 3000, 8000 — listing folderów, FTP',
  hintRouter:'Porty: 80, 443, 8080, 8443, 10000(Webmin)',
  hintNas:'Synology 5000/5001, QNAP 8080, Proxmox 8006, TrueNAS 80/443',
  hintAll:'Wszystkie znane porty jednocześnie — wolniejszy, najdokładniejszy',
  labelChecked:'Sprawdzono:', labelFound:'Znaleziono:', labelPorts:'Portów:',
  colIp:'Adres IP', colPing:'Ping', colHostname:'Hostname', colPorts:'Porty', colLinks:'Ścieżki / Linki',
  filterShow:'Pokaż:', filterAll:'Wszystkie', filterFavorites:'★ Ulubione', filterActive:'Aktywne', filterDead:'Martwe',
  emptyRow:'Brak wyników. Skonfiguruj zakres IP i kliknij Start.',
  emptyScanning:'Skanowanie…', emptyNone:'Nie znaleziono aktywnych hostów.',
  detailGeo:'🌍 Geolokalizacja / ISP', detailDevice:'🖥 Identyfikacja urządzenia',
  detailTitle:'📄 Tytuł strony HTTP', detailAccess:'🔑 Dostęp',
  geoLocal:'Adres lokalny — geolokalizacja niedostępna',
  geoError:'Błąd pobierania danych',
  geoCountry:'Kraj:', geoIsp:'ISP:', geoAs:'AS:',
  deviceFavicon:'Favicon:', deviceFaviconYes:'✔ Tak (panel webowy)', deviceFaviconNo:'✘ Brak',
  deviceType:'Typ:', deviceSuggestion:'Sugestia:', deviceUnknown:'Nieznany typ urządzenia',
  titleExtOnly:'Tytuł: tylko dla zewnętrznych IP', titleUnavailable:'Tytuł: niedostępny',
  titleLabel:'Tytuł strony:', accessLabel:'Zrzut:',
  accessOpen:'🔓 Dostępny bez hasła',
  accessClosed:'Wymaga autoryzacji lub brak',
  loading:'Pobieranie…', analyzing:'Analiza…', checking:'Sprawdzanie…',
  localSubnetsFound:(n)=>`Wykryto podsieci: ${n}`, localSubnetsNone:'Nie wykryto lokalnej podsieci',
  localDetectUnsupported:'Wykrywanie lokalnej sieci nie jest wspierane w tej przeglądarce/kontekście',
  localIpDetectError:'Nie udało się wykryć lokalnego IP (WebRTC zablokowane lub niedostępne)',
  previewOpen:'↗ Otwórz', previewClose:'✕',
  statusReady:'Gotowy.', statusCleared:'Wyczyszczono.',
  errInvalidIp:'Podaj poprawne adresy IPv4.',
  errIpRange:'Adres OD musi być ≤ DO.',
  closeConfirm:'Czy na pewno chcesz zamknąć skaner?',
  errNoPorts:'Wybierz co najmniej jeden port w presecie.',
  statusScanning:(n,p)=>`Skanuję ${n} adresów × ${p} portów…`,
  statusLarge:(n,p,t)=>`Duży zakres: ${n} adresów × ${p} portów. Est. ${t}…`,
  statusStopped:(n)=>`Zatrzymano po ${n} adresach.`,
  statusDone:(h,p)=>`Zakończono. Znaleziono ${h} hostów (${p} portów).`,
  statusNone:'Skan zakończony — brak aktywnych hostów.',
  statusHosts:(n)=>`${n} hostów`,
  ctxCopyIp:'Kopiuj adres IP', ctxCopyPorts:'Kopiuj porty', ctxHostname:'Hostname (reverse DNS)', ctxScanAllPorts:'Skanuj to IP (wszystkie porty)',
  ctxOpenBrowser:'Otwórz w przeglądarce', ctxPreview:'Podgląd tutaj',
  labelPreset:'Preset:', labelPorts2:'Porty:',
  presetAdd:'+ Dodaj', presetDel:'✕ Usuń',
  presetEdit:'Edytuj preset', presetName:'Nazwa:',
  presetPorts:'Porty:', presetSave:'💾 Zapisz',
  presetHint:'Wpisz numery portów po przecinku, np.: 80, 443, 8080, 554',
  dlgTitle:'Opcje', dlgLang:'Język:',
  dlgDefaults:'Domyślne wartości skanowania:', dlgDefaultThreads:'Wątki:', dlgDefaultDelay:'Opóźnienie (ms):', dlgDefaultDelayPerPort:'Opóźnienie na port (ms):',
  tipThreads:'Liczba równoległych wątków skanujących adresy IP (2–64). Więcej = szybciej, ale większe obciążenie sieci.',
  tipIpDelay:'Przerwa (ms) między kolejnymi adresami IP skanowanymi przez każdy wątek. 0 = brak opóźnienia.',
  tipBatchSize:'Liczba portów skanowanych jednocześnie w trybie równoległym (10–500). Większa paczka = szybciej, ale więcej połączeń naraz.',
  tipParallel:'Wszystkie porty w paczce skanowane są jednocześnie — najszybszy tryb.',
  tipSequential:'Porty skanowane są jeden po drugim z zadanym opóźnieniem — wolniej, ale mniej widoczne dla IDS/firewall.',
  tipPortDelay:'Przerwa (ms) między skanowaniem kolejnych portów w trybie sekwencyjnym (0–1000).',
  dlgLangEn:'English', dlgLangPl:'Polski',
  menuClippy:'📎 Asystent',
  dlgOk:'OK', dlgCancel:'Anuluj', dlgClose:'Zamknij', dlgVersionsTitle:'Wersje',
  dlgExternalIpTitle:'Zewnętrzny zakres IP', dlgExternalIpDetected:'Wykryto skanowanie zewnętrznych IP', dlgExternalIpContinue:'OK - Kontynuuj',
  dlgExternalIpMsg:(startIp, endIp)=>`Zakres <b>${startIp} - ${endIp}</b> zawiera <b>publiczne (zewnętrzne) adresy IP</b>.<br><br>Skanowanie zewnętrznych adresów bez autoryzacji może być nielegalne i niezgodne z regulaminem dostawcy Internetu.<br><br>Kontynuuj tylko wtedy, gdy jesteś właścicielem tych adresów lub masz wyraźną zgodę na skanowanie.`,
  dlgLargeRangeTitle:'Duży zakres skanowania', dlgLargeRangeHead:'Czy na pewno?',
  dlgLargeRangeMsg:(count)=>`Wybrany zakres zawiera ${count} adresów IP. Skanowanie dużego zakresu może potrwać długo. Czy chcesz kontynuować?`,
  portRtsp:'RTSP stream prawdopodobnie dostępny',
  portIpp:'Drukarka (IPP)', portRaw:'Drukarka (RAW)',
  portSyn:'Synology NAS?', portProx:'Proxmox VE?',
  tagVpn:'VPN/Proxy', tagDc:'Datacenter', tagRecognized:'ROZPOZNANY',
  notepadDesktop:'Notatnik',
  notepadWinTitle:'About',
  previewBlocked:'Urządzenie blokuje osadzanie (X-Frame-Options).',
  previewBlockedLink:'Otwórz w nowej karcie →',
  btnImportTrace:'Importuj Trace', btnClearGraph:'Wyczyść graf', graphCleared:'Trasy zostały wyczyszczone.', btnClearTopoFilters:'Wyczyść filtry', topoFiltersLabel:'Filtry:', mapLiveLabel:'Wizualizacja na żywo',
  filterAllPorts:'Wszystkie porty', filterPortLabel:'port', filterSubnetLabel:'podsieć', filterPingLabel:'ping', filterPingPlaceholder:'Maks ms',
  topologyStatus:(n)=>`Widok topologii · ${n} widocznych hostów`,
  topologyFilteredStatus:(n)=>`Widok topologii · ${n} hostów po filtrach`,
  traceRoutesLabel:'tras traceroute',
  traceDlgTitle:'Import traceroute', traceTargetLabel:'Docelowe IP:', traceHint:'Wklej wynik z tracert albo traceroute.', traceDlgHint:'Zaimportuj prawdziwą trasę hop-by-hop dla wybranego hosta.',
  traceErrTarget:'Podaj poprawny docelowy adres IPv4.', traceErrTargetOrHost:'Podaj poprawny docelowy adres IP lub hostname.', traceErrParse:'Nie udało się odczytać hopów z wklejonego wyniku.',
  traceImported:(n, ip)=>`Zaimportowano ${n} hopów dla ${ip}.`, traceImportedStatus:(ip, n)=>`Zaimportowano trasę dla ${ip} (${n} hopów).`, traceHopCopied:(ip)=>`Skopiowano IP hopa: ${ip}`,
  btnTraceAuto:'Auto Trace', traceAutoRunning:'Uruchamiam traceroute...', traceAutoDesktopOnly:'Auto trace działa tylko w wersji desktopowej Tauri.',
  traceAutoFailed:(msg)=>`Traceroute nie powiodło się: ${msg}`,
  btnTraceSave:'Importuj',
  menuEdit:'Edycja',
  cmdWinTitle:'Log konsoli', cmdMenuFile:'Plik', cmdSaveLogs:'💾 Zapisz logi...',
  cmdFilter:'Filtr:', cmdFilterAll:'-- Wszystko --', cmdFilterScan:'Skan',
  cmdFilterTracert:'Tracert', cmdFilterMacro:'Makro', cmdFilterSpeed:'Szybkość',
  cmdBtnFilter:'Filtruj', cmdBtnClearLog:'Wyczyść',
  speedWinTitle:'Test prędkości internetu',
  speedLabelDownload:'Pobieranie', speedLabelPing:'Ping', speedLabelUpload:'Wysyłanie',
  speedMbps:'Mbps', speedMs:'ms',
  speedReady:'Kliknij Start, aby zmierzyć ping, download i upload.',
  speedBtnStart:'▶ Start test',
  protoWinTitle:'Prototyp Visual Programming',
  protoStatusText:'Status: Tryb prototypu (tylko koncepcja UI). Tryb łączy: kliknij kotwicę OUT, potem IN.',
  macroWinTitle:'Makra', macroCtxDelete:'🗑 Skasuj makro',
  countrySearchPlaceholder:'Szukaj kraju…', countryRangeHint:'Kliknij zakres, a następnie kliknij Użyj.',
  btnCountryUse:'➤ Użyj zakresu', btnCountryUseAll:'➤ Użyj wszystkich',
  customizeTitle:'Dostosowanie – Pasek narzędzi', customizeToolbarLegend:'Przyciski paska',
  customizeGlobe:'🌍 Glob (Mapa świata)', customizeConsole:'⌨ Konsola',
  customizeMacro:'📁 Makro', customizeSpeed:'📶 Test prędkości',
  customizeProto:'🧩 Prototyp', customizeTopology:'🕸 Topologia',
  customizeSkinLegend:'Wygląd', skinClassic:'Klasyczny', skinGlass:'Szklany', skinWorkbench:'Ciemny motyw', skinPurpleDark:'Fioletowy ciemny', skinBlackFlat:'Czarny flat', skinRetrogray:'Retro szary',
  globeWinTitle:'Mapa sieci – Wyniki skanowania',
  topoWinTitle:'Topologia sieci',
  btnMapGlobe:'Glob', btnMapTopology:'Topologia',
  globeStatusDefault:'Przeciągnij aby obrócić · Kliknij kraj aby skanować · Kliknij punkt aby podejrzeć',
  topoStatusDefault:'Topologia · Kliknij host aby podejrzeć · Pierścienie = głębokość podsieci',
  globeAutoRotate:'Auto-obrót',
  scanCountryDlgTitle:'Skanuj kraj', dlgYes:'Tak', dlgNo:'Nie',
  ctxDetailGeo:'🌍 Geolokalizacja / ISP', ctxDetailDevice:'🖥 Identyfikacja urządzenia',
  ctxDetailTitle:'📄 Tytuł strony HTTP', ctxDetailAccess:'🔑 Dostęp / Snapshot',
  btnGnss:'🛰 GNSS', btnGnssMenu:'🛰 Monitor GNSS...',
  gnssWinTitle:'Monitor GNSS', gnssPort:'Port:', gnssBaud:'Baud:',
  gnssRefreshPorts:'Odśwież porty', gnssReadNow:'Odczytaj', gnssStartLive:'Start live', gnssStopLive:'Stop',
  gnssStatus:'Status GNSS', gnssSatMonitor:'Monitor satelitów', gnssConstellation:'Konstelacja',
  gnssWifiAudit:'Audyt GPS + WiFi', gnssWifiScan:'Skanuj WiFi', gnssAddPoint:'Dodaj punkt audytu', gnssExportAudit:'Eksport CSV',
  gnssReady:'Gotowy.', gnssBrowserGeo:'Geolokalizacja przeglądarki', gnssDesktopOnly:'Ta akcja wymaga trybu desktop (Tauri).',
  gnssPortsLoaded:(n)=>`Załadowano portów: ${n}.`, gnssErrPorts:(e)=>`Nie udało się wczytać portów: ${e}`,
  gnssFix:'Fix', gnssSatsUsed:'Satelity użyte', gnssSatsInView:'Satelity w zasięgu', gnssSource:'Źródło', gnssTimeUtc:'Czas UTC',
  gnssReading:'Odczyt danych GNSS...', gnssReadOk:'Dane GNSS zaktualizowane.', gnssErrRead:(e)=>`Błąd odczytu GNSS: ${e}`,
  gnssWifiOk:(n)=>`Skan WiFi zakończony. Sieci: ${n}.`, gnssErrWifi:(e)=>`Błąd skanowania WiFi: ${e}`,
  gnssNoAuditPoints:'Brak punktów audytu.', gnssNeedFix:'Aby dodać punkt audytu, potrzebny jest fix GNSS.',
  gnssPointAdded:(n)=>`Dodano punkt audytu (#${n}).`,
  btnLteMenu:'📶 Monitor LTE...', lteWinTitle:'Monitor LTE',
  lteRefresh:'Odśwież', lteStartLive:'Start live', lteStopLive:'Stop', lteLiveEvery:'Co (s):',
  ltePort:'Port:', lteBaud:'Baud:', lteAutoDetect:'Auto',
  lteModeAuto:'Auto', lteModeManual:'Ręczny',
  lteStatusTitle:'Monitor statusu LTE', lteHandoverTitle:'Tracker handover komórki',
  lteAuditTitle:'Audyt LTE + GPS', lteAddPoint:'Dodaj punkt', lteExportAudit:'Eksport CSV',
  lteCorrelationTitle:'Korelacja prędkości z jakością', lteRunSpeed:'Uruchom próbkę', lteExportCorrelation:'Eksport CSV',
  lteWatchdogTitle:'Watchdog internetu LTE', lteStartWatchdog:'Start watchdog', lteStopWatchdog:'Stop',
  lteReady:'Gotowy.', lteNoData:'Brak danych LTE/sieci.', lteStatusUpdated:'Status zaktualizowany.',
  lteQualityScore:'Ocena jakości', lteRadioTech:'Radio', lteEffectiveType:'Typ efektywny', lteConnType:'Typ połączenia',
  lteMode:'Tryb',
  lteOperator:'Operator', lteBand:'Pasmo', lteEarfcn:'EARFCN', lteCellId:'Cell ID', lteTac:'TAC',
  lteRsrp:'RSRP', lteRsrq:'RSRQ', lteSinr:'SINR', lteSource:'Źródło', lteSerialModeActive:'modem szeregowy',
  lteDownlink:'Downlink', lteRtt:'RTT', ltePublicIp:'Publiczne IP', lteLocalIp:'Lokalne IP', lteOnline:'Online', lteUpdatedAt:'Aktualizacja',
  lteNoHandover:'Brak handoverów.', lteHandoverReasonProfileChange:'zmienił się profil sieci',
  lteNoAuditPoints:'Brak punktów audytu.', lteAuditPointAdded:(n)=>`Dodano punkt audytu (#${n}).`,
  lteNoCorrelation:'Brak próbek korelacji.', lteCorrAdded:(n)=>`Dodano próbkę korelacji (#${n}).`,
  lteCorrInsufficient:'Korelacja: wymagane co najmniej 3 próbki.', lteCorrNow:'Korelacja (jakość vs download)',
  lteWatchdogEmpty:'Brak zdarzeń watchdoga.', lteWatchdogFail:'Watchdog: wykryto problem z łącznością.',
  lteWatchdogOk:(rtt)=>`Watchdog OK (${rtt} ms).`, lteWdOk:'OK', lteWdFail:'FAIL',
  btnSniffer:'🔎 Sniffer', btnSnifferMenu:'🔎 Sniffer sieciowy...',
  snifferWinTitle:'Sniffer sieciowy',
  snifferAll:'Wszystko', snifferRefresh:'↻ Odśwież', snifferLive:'Live', snifferExport:'💾 Eksport CSV',
  snifferColPid:'PID', snifferColProc:'Proces', snifferColProto:'Proto',
  snifferColLocal:'Lokalny', snifferColRemote:'Zdalny', snifferColState:'Stan',
  snifferFilter:'Filtruj proces / IP...',
  snifferReady:'Gotowy.', snifferLoading:'Odświeżam połączenia...',
  snifferStatusDone:(n)=>`Załadowano połączeń: ${n}.`,
  snifferEmpty:'Brak połączeń pasujących do filtra.',
  snifferDesktopOnly:'Sniffer działa tylko w wersji desktopowej (Tauri).',
  snifferTotal:'Razem',
  btnImgMetaMenu:'🖼 Metadane obrazów...', imgMetaWinTitle:'Analizator metadanych i steganografii obrazów',
  imgMetaDropHint:'Upuść obraz tutaj lub kliknij, aby wybrać',
  imgMetaBrowse:'Przeglądaj...', imgMetaClear:'Wyczyść', imgMetaClearAll:'Wyczyść wszystko', imgMetaZeroValues:'Wyzeruj wartości', imgMetaCopy:'Kopiuj', imgMetaExport:'Eksport TXT',
  imgMetaHideEmptyOn:'Ukryj puste: WŁ.', imgMetaHideEmptyOff:'Ukryj puste: WYŁ.', imgMetaHideEmptyHint:'Ukrywa lub pokazuje wykryte pola metadanych z pustą wartością.',
  imgMetaSection:'Sekcja', imgMetaKey:'Pole', imgMetaValue:'Wartość',
  imgMetaReady:'Gotowy. Otwórz obraz, aby przeanalizować metadane (sprawdzanie steganografii włączone).',
  imgMetaLoading:'Odczytuję plik...', imgMetaAnalyzing:'Analizuję...',
  imgMetaDone:(n)=>`Znaleziono ${n} pole(i) metadanych.`,
  imgMetaNoMeta:'Nie znaleziono metadanych w tym pliku.',
  imgMetaStegoChecked:'Sprawdzanie steganografii włączone.',
  imgMetaStegoNotDetected:'Nie wykryto ukrytych danych końcowych.',
  imgMetaStegoDetected:(n)=>`Wykryto potencjalnie ukryte dane końcowe: ${n} bajt(ów).`,
  imgMetaDesktopHint:'Pełne dane EXIF i GPS wymagają trybu desktopowego (Tauri).',
  btnPhoneLookupMenu:'📱 Wsteczne wyszukiwanie numeru...', phoneLookupWinTitle:'Wsteczne wyszukiwanie numeru telefonu',
  phoneLookupApiSetup:'Przewodnik konfiguracji API',
  phoneLookupApiKeys:'Konfiguracja kluczy API',
  phoneLookupInput:'Numer telefonu', phoneLookupSearchBtn:'Szukaj',
  phoneLookupReady:'Gotowy. Wpisz numer telefonu, aby wyszukać informacje.',
  btnSave:'Zapisz', btnClear:'Wyczyść',
  imgMetaErrRead:'Nie udało się odczytać pliku.',
  imgMetaInfo:'Info', imgMetaInfoTitle:'Analizowane pola metadanych',
  imgMetaEdited:'Zmiana zapisana lokalnie.',
  imgMetaCopied:'Skopiowano do schowka.',
};
